name: flutter_bluegps_sdk
description: BlueGPS SDK for Flutter - Quuppa indoor positioning and BlueGPS server integration.
version: 0.1.0
publish_to: none
homepage: https://github.com/synapseslab/flutter-bluegps-sdk

environment:
  sdk: ^3.6.1
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  bgps_flutter_ios_quuppa_driver:
    git:
      url: https://github.com/synapseslab/ios-bgps-quuppa-flutter-plugin.git
      ref: e0a0129fb5b1d23369ff02bb91b14282e573c44a
  bgps_flutter_android_quuppa_driver:
    git:
      url: https://github.com/synapseslab/android-bgps-quuppa-flutter-plugin.git
      ref: 347eaf93431d1015300a1e51771b3897df012e3f
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
