name: flutter_bluegps_sdk
description: BlueGPS SDK for Flutter - Quuppa indoor positioning and BlueGPS server integration.
version: 1.0.0-beta.1
publish_to: none
homepage: https://github.com/synapseslab/flutter-bluegps-sdk

environment:
  sdk: ^3.6.1
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  bgps_flutter_ios_quuppa_driver:
    path: dist/bgps_flutter_ios_quuppa_driver
  bgps_flutter_android_quuppa_driver:
    path: dist/bgps_flutter_android_quuppa_driver
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
