name: flutter_bluegps_sdk
description: BlueGPS SDK for Flutter Applications - A Flutter plugin for integrating BlueGPS indoor positioning system in iOS and Android applications.
version: 0.0.1
homepage: https://github.com/synapseslab/flutter-bluegps-sdk

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.synapseslab.flutter_bluegps_sdk
        pluginClass: FlutterBluegpsSdkPlugin
      ios:
        pluginClass: FlutterBluegpsSdkPlugin
